compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmRegistryServer: 'https://registry.yarnpkg.com'

npmScopes:
  rocketleap:
    npmAlwaysAuth: true
    npmAuthToken: '${GITHUB_TOKEN}'
    npmPublishRegistry: 'https://npm.pkg.github.com'
    npmRegistryServer: 'https://npm.pkg.github.com'

yarnPath: .yarn/releases/yarn-4.9.2.cjs
