export const COMPILE_CONFIGURATION = {
  tsconfig: {
    compilerOptions: {
      alwaysStrict: true,
      declaration: true,
      esModuleInterop: true,
      experimentalDecorators: true,
      inlineSourceMap: true,
      inlineSources: true,
      lib: ['es2020'],
      module: 'CommonJS',
      noEmitOnError: false,
      noFallthroughCasesInSwitch: true,
      noImplicitAny: true,
      noImplicitReturns: true,
      noImplicitThis: true,
      noUnusedLocals: true,
      noUnusedParameters: true,
      resolveJsonModule: true,
      strict: true,
      strictNullChecks: true,
      strictPropertyInitialization: true,
      stripInternal: true,
      target: 'ES2020',
    },
    include: ['src/**/*.ts', 'bin/**/*ts'],
    exclude: ['cdk.out', 'node_modules'],
  },
  tsconfigDev: {
    compilerOptions: {
      alwaysStrict: true,
      declaration: true,
      esModuleInterop: true,
      experimentalDecorators: true,
      sourceMap: true,
      inlineSourceMap: true,
      inlineSources: true,
      lib: ['es2020'],
      module: 'CommonJS',
      noEmitOnError: false,
      noFallthroughCasesInSwitch: true,
      noImplicitAny: true,
      noImplicitReturns: true,
      noImplicitThis: true,
      noUnusedLocals: true,
      noUnusedParameters: true,
      resolveJsonModule: true,
      strict: true,
      strictNullChecks: true,
      strictPropertyInitialization: true,
      stripInternal: true,
      target: 'ES2020',
    },
    include: ['src/**/*.ts', 'bin/**/*ts', 'test/**/*.ts'],
  },
};
